disabled_rules: # rule identifiers to exclude from running
  - line_length
  - identifier_name
  - superfluous_disable_command
opt_in_rules:
  - closing_brace
  - closure_end_indentation
  - closure_spacing
  - colon
  - comma
  - empty_enum_arguments
  - empty_parameters
  - empty_parentheses_with_trailing_closure
  - explicit_init
  - implicit_return
  - joined_default_parameter
  - leading_whitespace
  - legacy_cggeometry_functions
  - legacy_constant
  - legacy_constructor
  - legacy_nsgeometry_functions
  - literal_expression_end_indentation
  - mark
  - multiple_closures_with_trailing_closure
  - nimble_operator
  - number_separator
  - opening_brace
  - operator_usage_whitespace
  - private_over_fileprivate
  - protocol_property_accessors_order
  - redundant_discardable_let
  - redundant_nil_coalescing
  - redundant_optional_initialization
  - redundant_void_return
  - return_arrow_whitespace
  - sorted_imports
  - statement_position
  - trailing_comma
  - trailing_newline
  - trailing_semicolon
  - trailing_whitespace
  - unneeded_parentheses_in_closure_argument
  - untyped_error_in_catch
  - unused_closure_parameter
  - vertical_whitespace
  - void_return
indentation: 2
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
identifier_name:
  min_length: # only min_length
    warning: 2 # only error
